# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.

  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "hashicorp/precise64"

  # VirtualBox specific configuration.
    config.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", "2048"]
      vb.customize ["modifyvm", :id, "--cpus", "2"]
    end

  # If true, then any SSH connections made will enable agent forwarding.
  # Default value: false
  config.ssh.forward_agent = true

  config.vm.network :private_network, ip: "10.1.0.10"
  config.vm.synced_folder "../workspace", "/home/vagrant/workspace",
    type: "nfs", create: true
  config.vm.synced_folder "../finished", "/home/vagrant/finished",
    type: "nfs", create: true

  # provision using ansible
  # config.vm.provision "ansible" do |ansible|
  #   ansible.playbook = "provisioning/playbook.yml"
  # end

  # some setup tasks run with privileged
  config.vm.provision :shell, path: "drupal-setup/install.sh", privileged: false


  # Forwarded ports
  config.vm.network "forwarded_port", guest: 3000, host: 3000
  config.vm.network "forwarded_port", guest: 3001, host: 3001
  config.vm.network "forwarded_port", guest:8080, host:8080
  config.vm.network "forwarded_port", guest:8081, host:8081
  config.vm.network "forwarded_port", guest:80, host:80
end
